version: 2
jobs:
  build:
    docker:
      - image: crystallang/crystal:nightly
    steps:
      - checkout
      - run: shards install
      - run:
          name: Prep test-results folder
          command: mkdir -p /tmp/test-results/spec            
      - run:
          name: Show Crystal version
          command: crystal -v > /tmp/test-results/crystal_version.txt
      - run:
          name: Show repo version
          command: scripts/version_info > /tmp/test-results/app_version.txt
      - run:
          name: Run static code analysis
          command: bin/ameba --no-color > /tmp/test-results/static_code_analysis.ameba.txt
      - run:
          name: run tests (txt format)
          command: scripts/test_always > /tmp/test-results/spec/results.txt
      - run:
          name: run tests (junit format)
          command: scripts/test_always_junit_format
      # This times out and breaks the build:
      # - run:
      #     name: Run benchmarks
      #     command: scripts/bench > test-results/bench.txt
      # - run:
      #     name: List test_results files
      #     command: |
      #       apt install -y tree
      #       tree test-results

      # # collect reports
      # - store_test_results:
      #     path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          # destination: test-results
