name: Crystal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:nightly

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: shards install
    - name: Show Crystal version
      run: crystal -v
    - name: Show repo version
      run: scripts/version_info
    #   # TODO: re-enable ameba after that shard is updated for Crystal 1.0 compatibility
    # - name: Run static code analysis
    #   run: bin/ameba --no-color
    - name: Run tests
      run: scripts/test_always
      # run: crystal spec
    - name: Run tests (w/ junit format)
      run: scripts/test_always_junit_format
